### ISSUE TITLE
Cannot compile on Jetpack 6.1

### ISSUE THREAD

**Issue by 0ct0cat** [NVIDIA-AI-IOT/NVIDIA-Optical-Character-Detection-and-Recognition-Solution#21]
```
src/TRTEngine.cpp: In member function ‘size_t nvocdr::TRTEngine::getTrtIoTensorDtypeSizeByName(std::string&)’:
src/TRTEngine.cpp:187:33: error: ‘class nvinfer1::ICudaEngine’ has no member named ‘getBindingIndex’
  187 |     int bindingIndex = mEngine->getBindingIndex(tensorName.c_str());
      |                                 ^~~~~~~~~~~~~~~
src/TRTEngine.cpp:192:44: error: ‘class nvinfer1::ICudaEngine’ has no member named ‘getBindingDataType’; did you mean ‘getTensorDataType’?
  192 |     nvinfer1::DataType dataType = mEngine->getBindingDataType(bindingIndex);
      |                                            ^~~~~~~~~~~~~~~~~~
      |                                            getTensorDataType
make: *** [Makefile:93: chobj/TRTEngine.o] Error 1
```

It seems that the API of TRT-8.0 is used, which makes it impossible to compile on TRT-10.

**Comment by Tyler-D** [comment]
Closed as #22 merged.
